name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - gh-pages  # Trigger workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18  # Use Node.js version 18

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Build the Angular project
    - name: Build Angular project
      run: npm run build --configuration=prod

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      run: npx angular-cli-ghpages --dir=dist/angular-app/browser --no-silent
